import { MenuItem, Port, AccountGroup } from './types';

export const PORTS: Port[] = [
  { id: '1', name: 'CN CÔNG TY CP CẢNG SÀI GÒN' },
  { id: '2', name: 'CẢNG TÂN THUẬN' },
  { id: '3', name: 'CẢNG HIỆP PHƯỚC' },
];

export const ACCOUNT_GROUPS: AccountGroup[] = [
  { id: 'ban_ke_toan', name: 'BAN KẾ TOÁN' },
  { id: 'ban_kd_kt', name: 'BAN KINH DOANH KHAI THÁC' },
  { id: 'doi_co_gioi', name: 'ĐỘI CƠ GIỚI' },
  { id: 'doi_kho_hang', name: 'ĐỘI KHO HÀNG' },
  { id: 'doi_bao_ve', name: 'ĐỘI BẢO VỆ' },
  { id: 'nhom_admin', name: 'Nhóm Admin' },
  { id: 'nhom_chu_tau', name: 'Nhóm chủ tàu' },
  { id: 'khach_hang', name: 'Khách hàng' },
  { id: 'quan_tri', name: 'QUẢN TRỊ' },
  { id: 'tally', name: 'TALLY' },
  { id: 'truc_ban_sx', name: 'TRUC BAN SAN XUAT' },
  { id: 'to_co_gioi_1', name: 'TỔ CƠ GIỚI 1' },
  { id: 'to_co_gioi_3', name: 'TỔ CƠ GIỚI 3' },
  { id: 'tong_hop', name: 'TỔNG HỢP' },
  { id: 'truck', name: 'TRUCK' },
  { id: 'yard', name: 'YARD' },
];

export const INITIAL_DATA: MenuItem[] = [
  {
    id: 1,
    stt: 1,
    name: 'QUẢN TRỊ HỆ THỐNG',
    parentCode: '',
    isHeader: true,
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 2,
    stt: 2,
    name: 'Nhóm người dùng',
    parentCode: 'Users_Management',
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 3,
    stt: 3,
    name: 'Người dùng',
    parentCode: 'Users_Management',
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 4,
    stt: 4,
    name: 'Phân quyền',
    parentCode: 'Users_Management',
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 5,
    stt: 5,
    name: 'DANH MỤC',
    parentCode: '',
    isHeader: true,
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 6,
    stt: 6,
    name: 'Loại hàng hóa',
    parentCode: 'Common',
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 7,
    stt: 7,
    name: 'Hàng hóa',
    parentCode: 'Common',
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 8,
    stt: 8,
    name: 'Loại tổ đội công nhân',
    parentCode: 'Common',
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 9,
    stt: 9,
    name: 'Tổ đội công nhân',
    parentCode: 'Common',
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 10,
    stt: 10,
    name: 'Ca làm việc',
    parentCode: 'Common',
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 11,
    stt: 11,
    name: 'Loại khách hàng',
    parentCode: 'Common',
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 12,
    stt: 12,
    name: 'Thiết bị',
    parentCode: 'Common',
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 13,
    stt: 13,
    name: 'Loại thiết bị',
    parentCode: 'Common',
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 14,
    stt: 14,
    name: 'Khách hàng',
    parentCode: 'Common',
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 15,
    stt: 15,
    name: 'Bãi',
    parentCode: 'Common',
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 16,
    stt: 16,
    name: 'Định nghĩa sơ đồ bãi',
    parentCode: 'Common',
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 17,
    stt: 17,
    name: 'Bến',
    parentCode: 'Common',
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 18,
    stt: 18,
    name: 'Bitt',
    parentCode: 'Common',
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 19,
    stt: 19,
    name: 'Cảng',
    parentCode: 'Common',
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 20,
    stt: 20,
    name: 'Cổng',
    parentCode: 'Common',
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 21,
    stt: 21,
    name: 'Tỷ giá',
    parentCode: 'Common',
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 22,
    stt: 22,
    name: 'Dịch vụ',
    parentCode: 'Common',
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 23,
    stt: 23,
    name: 'Quốc gia',
    parentCode: 'Common',
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 24,
    stt: 24,
    name: 'Vùng phụ',
    parentCode: 'Common',
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 25,
    stt: 25,
    name: 'Đơn vị tính',
    parentCode: 'Common',
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 26,
    stt: 26,
    name: 'Phương án',
    parentCode: 'Common',
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 27,
    stt: 27,
    name: 'Phương án xếp dỡ',
    parentCode: 'Common',
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 28,
    stt: 28,
    name: 'Loại công việc',
    parentCode: 'Common',
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 29,
    stt: 29,
    name: 'Hãng khai thác',
    parentCode: 'Common',
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 30,
    stt: 30,
    name: 'Hướng nhập xuất',
    parentCode: 'Common',
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 31,
    stt: 31,
    name: 'Loại hình thanh toán',
    parentCode: 'Common',
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 32,
    stt: 32,
    name: 'Hình thức thanh toán',
    parentCode: 'Common',
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 33,
    stt: 33,
    name: 'Loại hình vận chuyển',
    parentCode: 'Common',
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 34,
    stt: 34,
    name: 'Quy cách',
    parentCode: 'Common',
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 35,
    stt: 35,
    name: 'KẾ HOẠCH KHAI THÁC',
    parentCode: '',
    isHeader: true,
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 36,
    stt: 36,
    name: 'Kế hoạch bãi',
    parentCode: 'Vessel',
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 37,
    stt: 37,
    name: 'Định nghĩa tàu',
    parentCode: 'Vessel',
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 38,
    stt: 38,
    name: 'Kế hoạch cầu bến',
    parentCode: 'Vessel',
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 39,
    stt: 39,
    name: 'Giám sát cầu bến',
    parentCode: 'Vessel',
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 40,
    stt: 40,
    name: 'Kế hoạch PTTB Nhập',
    parentCode: 'Vessel',
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 41,
    stt: 41,
    name: 'Hành trình tàu',
    parentCode: 'Vessel',
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 42,
    stt: 42,
    name: 'KẾ HOẠCH BÃI',
    parentCode: '',
    isHeader: true,
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 43,
    stt: 43,
    name: 'HỢP ĐỒNG - BIỂU CƯỚC',
    parentCode: '',
    isHeader: true,
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 44,
    stt: 44,
    name: 'BÁO CÁO',
    parentCode: '',
    isHeader: true,
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 45,
    stt: 45,
    name: 'Phát hành hóa đơn',
    parentCode: 'Report',
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 46,
    stt: 46,
    name: 'Hủy hóa đơn',
    parentCode: 'Report',
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 47,
    stt: 47,
    name: 'Dữ liệu cảng',
    parentCode: 'Report',
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 48,
    stt: 48,
    name: 'Điều chỉnh/Thay thế hóa đơn',
    parentCode: 'Report',
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 49,
    stt: 49,
    name: 'In phiếu giao nhận',
    parentCode: 'Report',
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 50,
    stt: 50,
    name: 'In lại chứng từ',
    parentCode: 'Report',
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 51,
    stt: 51,
    name: 'Lịch sử thay đổi dữ liệu',
    parentCode: 'Report',
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 52,
    stt: 52,
    name: 'Tạo hoá đơn tay',
    parentCode: 'Report',
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 53,
    stt: 53,
    name: 'Biên bản kết toán tàu',
    parentCode: 'Report',
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 54,
    stt: 54,
    name: 'Ra vào cổng',
    parentCode: 'Report',
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 55,
    stt: 55,
    name: 'Nhập xuất tàu',
    parentCode: 'Report',
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 56,
    stt: 56,
    name: 'Tồn kho bãi',
    parentCode: 'Report',
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 57,
    stt: 57,
    name: 'Khai thác cầu bến',
    parentCode: 'Report',
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 58,
    stt: 58,
    name: 'Doanh thu hóa đơn',
    parentCode: 'Report',
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 59,
    stt: 59,
    name: 'Doanh thu theo khách hàng',
    parentCode: 'Report',
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 60,
    stt: 60,
    name: 'Sản lượng theo hầm',
    parentCode: 'Report',
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 61,
    stt: 61,
    name: 'Kiểm nhận hàng với tàu',
    parentCode: 'Report',
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 62,
    stt: 62,
    name: 'Danh sách hàng hóa nhập tàu',
    parentCode: 'Report',
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 63,
    stt: 63,
    name: 'Sản lượng phương tiện thiết bị',
    parentCode: 'Report',
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 64,
    stt: 64,
    name: 'Kiểm đếm hàng trong kho',
    parentCode: 'Report',
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 65,
    stt: 65,
    name: 'Hàng hóa nhập xuất',
    parentCode: 'Report',
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 66,
    stt: 66,
    name: 'Bảng kê xuất hàng',
    parentCode: 'Report',
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 67,
    stt: 67,
    name: 'Phiếu bàn giao ca',
    parentCode: 'Report',
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 68,
    stt: 68,
    name: 'Thay đổi công việc cổng',
    parentCode: 'Report',
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 69,
    stt: 69,
    name: 'Thay đổi công việc tàu',
    parentCode: 'Report',
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 70,
    stt: 70,
    name: 'THỦ TỤC',
    parentCode: '',
    isHeader: true,
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 71,
    stt: 71,
    name: 'KHÁC',
    parentCode: '',
    isHeader: true,
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 72,
    stt: 72,
    name: 'Mã biểu cước',
    parentCode: 'Job',
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 73,
    stt: 73,
    name: 'Dữ liệu cảng',
    parentCode: 'Job',
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 74,
    stt: 74,
    name: 'Xếp dỡ hàng với tàu',
    parentCode: 'Job',
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 75,
    stt: 75,
    name: 'Mẫu biểu cước',
    parentCode: 'Job',
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 76,
    stt: 76,
    name: 'Giao nhận cổng',
    parentCode: 'Job',
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 77,
    stt: 77,
    name: 'Lệnh dịch vụ',
    parentCode: 'Job',
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 78,
    stt: 78,
    name: 'Biểu cước chuẩn',
    parentCode: 'Job',
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 79,
    stt: 79,
    name: 'Hợp đồng',
    parentCode: 'Job',
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 80,
    stt: 80,
    name: 'Dữ liệu cảng',
    parentCode: 'Job',
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 81,
    stt: 81,
    name: 'Dịch vụ tại bãi',
    parentCode: 'Job',
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 82,
    stt: 82,
    name: 'Phí cầu bến',
    parentCode: 'Job',
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 83,
    stt: 83,
    name: 'Truy vấn thông tin lệnh',
    parentCode: 'Job',
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 84,
    stt: 84,
    name: 'Phí lưu bãi',
    parentCode: 'Job',
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 85,
    stt: 85,
    name: 'Giao nhận kho hàng',
    parentCode: 'Job',
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 86,
    stt: 86,
    name: 'CÔNG CỤ',
    parentCode: '',
    isHeader: true,
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 87,
    stt: 87,
    name: 'THAY ĐỔI DỮ LIỆU',
    parentCode: '',
    isHeader: true,
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 88,
    stt: 88,
    name: 'Dữ liệu cảng',
    parentCode: 'Changes',
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 89,
    stt: 89,
    name: 'GATE',
    parentCode: '',
    isHeader: true,
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 90,
    stt: 90,
    name: 'TALLY',
    parentCode: '',
    isHeader: true,
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 91,
    stt: 91,
    name: 'TRUCK',
    parentCode: '',
    isHeader: true,
    permissions: { view: true, add: true, edit: true, delete: true },
  },
  {
    id: 92,
    stt: 92,
    name: 'YARD',
    parentCode: '',
    isHeader: true,
    permissions: { view: true, add: true, edit: true, delete: true },
  },
];